import type { Metadata } from "next";
import "./styles/globals.scss";
import { ColorSchemeScript, MantineProvider } from "@mantine/core";
import { theme } from "../theme";

import "@mantine/core/styles.css";
import StoreProvider from "./_utils/redux/StoreProvider";
import { montserrat } from "./_globals/fonts";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="en">
            <head>
                <ColorSchemeScript />
            </head>
            <body className={montserrat.className}>
                <StoreProvider>
                    <MantineProvider theme={theme}>{children}</MantineProvider>
                </StoreProvider>
            </body>
        </html>
    );
}
