import type { Metadata } from "next";

import { ColorSchemeScript, MantineProvider } from "@mantine/core";
import { theme } from "../theme";
import { montserrat } from "./_globals/fonts";
import "@mantine/carousel/styles.css";
import "@mantine/core/styles.css";
import "./styles/globals.scss";
import styles from "./root.module.scss";

import StoreProvider from "./_utils/redux/StoreProvider";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="en">
            <head>
                <ColorSchemeScript />
            </head>
            <body
                className={`${montserrat.className} ${styles.rootStyle} `}
                id="root"
            >
                <StoreProvider>
                    <MantineProvider theme={theme}>{children}</MantineProvider>
                </StoreProvider>
            </body>
        </html>
    );
}
