import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./styles/globals.scss";
import { ColorSchemeScript, MantineProvider } from "@mantine/core";
import { theme } from "../theme";

import "@mantine/core/styles.css";
import StoreProvider from "./_utils/redux/StoreProvider";
// const inter = Inter({ subsets: ["latin"] });
// const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="en">
            <head>
                <ColorSchemeScript />
                {/* <meta
                    name="viewport"
                    content="minimum-scale=1, initial-scale=1, width=device-width, user-scalable=no"
                /> */}
            </head>
            <body>
                <StoreProvider>
                    <MantineProvider theme={theme}>{children}</MantineProvider>
                </StoreProvider>
            </body>
        </html>
    );
}
